// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "readingTime.enable": boolean;
      "readingTime.sampleIntervalMs": number;
      "readingTime.hangGuardMs": number;
      "readingTime.idleResetMs": number;
      "readingTime.persistDebounceMs": number;
      "titleColumn.enable": boolean;
      "titleColumn.heat.enable": boolean;
      "titleColumn.heat.hue": number;
      "titleColumn.heat.maxAlpha": string;
      "titleColumn.heat.scale": string;
      "titleColumn.icon.enable": boolean;
      "titleColumn.striping.enable": boolean;
      "titleColumn.tagSwatches.enable": boolean;
      "titleColumn.tagSwatches.max": number;
      "titleColumn.bold.scope": string;
      "creatorColumn.enable": boolean;
      "creatorColumn.template": string;
      "creatorColumn.join": string;
      "creatorColumn.slice": string;
      "creatorColumn.ellipsis": string;
      "collectionCounts.enable": boolean;
      "collectionCounts.mode": string;
      "progressColumn.enable": boolean;
      "progressColumn.style": string;
      "progressColumn.source": string;
      "progressColumn.normalize": string;
      "progressColumn.color": string;
      "progressColumn.maxBuckets": number;
      "readState.enable": boolean;
      "readState.boldAllItems": boolean;
      "readState.wholeRow": boolean;
      "readState.readKeys": string;
      "graphView.enable": boolean;
      "graphView.mode": string;
      "graphView.scope": string;
      "graphView.theme": string;
      "graphView.nodeCap": number;
      "graphView.showLabels": boolean;
      "graphView.charge": number;
      "graphView.linkDistance": number;
    };
  }
}
